### ISSUE TITLE
Shop disappearing 

### ISSUE THREAD

**Issue by ghost** [ExterminatorX99/ShopExpander#1]
I'm playing on Terraria v1.4.3.6 and tModLoader v2022.6.96.4.

As seen in the screenshots, vanilla and modded npcs have their shops completely removed and only 2 slots are there. It started happening when I unloaded Calamity's Vanities and Compare Item Stats mod (I tested removing some mods that may be causing incompatibility issues but that doesn't seem to be the problem). I've been playing like normal without any issues for around 10 hours in the same world and player without any issues until then.

Additionally, when I try to click on the 2nd slot on any vanilla or modded npc, it seems to remove all my buffs, the cursor disappears, and I can't move. When I put the "invisible" item inside my inventory, or even the trash slot, it does what is shown in the 2nd picture. I need to throw away the "invisible" item to get back to normal.

I've tried reloading the mods and also restarting tModLoader but to no avail. I also tried deleting then recovering with the backup world and player but it still happens.

Here are the logs:
[tModLoader-Logs.zip](https://github.com/ExterminatorX99/ShopExpander/files/9054118/tModLoader-Logs.zip)

![image](https://user-images.githubusercontent.com/94040719/177535026-b5838a85-bed4-40a9-ba0b-55578c749a0a.png)

![image (2)](https://user-images.githubusercontent.com/94040719/177535080-64448987-ee0e-4b05-941b-bf56eca6b4e2.png)

Also thanks for responding.

**Comment by ExterminatorX99** [comment]
Try disabling calamity

**Comment by ExterminatorX99** [comment]
Release an update. Try it and see if it helped

**Comment by ghost** [comment]
It seemed to have fixed it.

Edit: I only saw now that it updated, I'll check to see if it still happens with Calamity.

Here are the logs again in case if you need it.
[tModLoader-Logs.zip](https://github.com/ExterminatorX99/ShopExpander/files/9060290/tModLoader-Logs.zip)


![image](https://user-images.githubusercontent.com/94040719/177688006-712aee23-a7b7-4da7-ad0e-31b4bdd5fd61.png)

![image](https://user-images.githubusercontent.com/94040719/177688039-f6d0ed96-dbe0-4346-a900-d32c2d6e976a.png)

**Comment by ghost** [comment]
It works perfectly fine now. Thanks.

**Comment by ExterminatorX99** [comment]
After many complaints the changes were completely reverted.
Painter back to vanilla behaviour

**Comment by ghost** [comment]
Painter? What do you mean?

**Comment by ExterminatorX99** [comment]
The bugs were caused by me trying to fix the vanilla painter shop sometimes overflowing
